### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by morgoth**
* `aws-sdk` was not used at all
* There is no need for complex `require_all` gem
* No need for requiring whole active_support lib (only concern module is used)
* Added default rspec rake task

### CODE REVIEW

**Comment by morgoth** [comment]
@barelyknown Let me know if something is unclear here

**Comment by morgoth** [comment]
@barelyknown Is there anything more I can do to get this merged and released in new version?

**Comment by barelyknown** [comment]
I didn't notice this! Sorry about that. I'll merge now.

**Comment by morgoth** [comment]
@barelyknown Thanks. Can we have a gem release?

**Pull request merged**
